// Sanchoy Firebase Client Configuration & Setup Service
// Manages:
// - Reading configuration from firebase-applet-config.json, environment variables, or local storage
// - Detecting availability of Firebase project setup
// - Providing clean fallback for local/offline execution without crashes

import { safeStorage } from '../core/state.js';

const FIREBASE_CONFIG_STORAGE_KEY = 'sanchoy_firebase_client_config_v1';

// Default / fallback configuration structure
export const defaultFirebaseConfig = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  firestoreDatabaseId: "(default)"
};

let cachedConfig = null;

/**
 * Loads the active Firebase configuration
 */
export async function getFirebaseConfig() {
  if (cachedConfig) return cachedConfig;

  // 1. Try reading from firebase-applet-config.json if generated by provisioning
  try {
    const res = await fetch('/firebase-applet-config.json');
    if (res.ok) {
      const json = await res.json();
      if (json && (json.apiKey || json.projectId)) {
        cachedConfig = {
          ...defaultFirebaseConfig,
          ...json
        };
        return cachedConfig;
      }
    }
  } catch (e) {
    // Ignore fetch error in offline/local mode
  }

  // 2. Check local storage override if configured by user/developer
  try {
    const saved = safeStorage.getItem(FIREBASE_CONFIG_STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      if (parsed && (parsed.apiKey || parsed.projectId)) {
        cachedConfig = { ...defaultFirebaseConfig, ...parsed };
        return cachedConfig;
      }
    }
  } catch (e) {
    // Ignore parse error
  }

  return null;
}

/**
 * Saves a custom Firebase config to local storage
 */
export function setCustomFirebaseConfig(config) {
  cachedConfig = { ...defaultFirebaseConfig, ...config };
  safeStorage.setItem(FIREBASE_CONFIG_STORAGE_KEY, JSON.stringify(cachedConfig));
}

/**
 * Checks if Firebase has valid configuration available
 */
export async function isFirebaseConfigured() {
  const cfg = await getFirebaseConfig();
  return !!(cfg && cfg.apiKey && cfg.projectId);
}
